version: "3.7"
services:
  dis-portal-ws:
    container_name: dis-portal-ws
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4040:4040"
    env_file:
      - .env
